# Generated by Django 3.0 on 2019-12-20 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191219_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_htmml',
            field=models.TextField(blank=True, editable=False, verbose_name='正文html代码'),
        ),
    ]
