# Generated by Django 3.0 on 2019-12-20 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_content_htmml'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content_htmml',
            new_name='content_html',
        ),
    ]
